Contact-form on profile-project
Moise-code/Portfolio-website pull request #4
Opened 2022-09-28 12:48 UTC by Moise-code

In this Contact-form on profile-project :

   - My partner have added the html structure of the form and validation 
   - I have added the styling of the form
   - I have added the icons on the footer.

2022-09-28 13:11 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f574770523531743971623739534e464f74732f67697068792e676966](https://user-images.githubusercontent.com/93039359/190567385-8e7bb3c0-7d3b-4d25-8385-61d173233786.gif)

## Hey @Moise-code, @boo-shehab :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Following some requirements
:heavy_check_mark: Meaningful commit messages
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 13:11 UTC, HAMMAS-SALEEM commented on index.html
> +    <form action="">
- [ ] Kindly replace this `h1` with `h2` tag because each html page should have only one `h1` which you already have at the homepage of your portfolio. It is important to follow the [heading hierarchy](https://www.w3.org/WAI/test-evaluate/preliminary/#headings) due to SEO purpose :blush:

2022-09-28 13:11 UTC, HAMMAS-SALEEM commented on index.html
> +    <form action="">
### Missing Requirements :memo:
![missing-req-contact-form](https://user-images.githubusercontent.com/93039359/192786008-8b36838e-680e-4269-b586-f2741af89f6e.png)


- [ ] You didn't implement formspree in your contact form and that's a requirement in your project. Kindly implement the [Formspree service](https://formspree.io/html) to make your contact form work. :+1:

2022-09-28 13:11 UTC, HAMMAS-SALEEM commented on index.html
> +    </form>
### Missing Button :record_button:
![Screenshot from 2022-09-28 17-57-39 (copy)](https://user-images.githubusercontent.com/93039359/192786744-60604a34-da4d-4dd1-a5b3-8b72546fd4ee.png)


- [ ] I was thinking that how i'm gonna submit my form then i saw that there is not submit button :smile: No problem you can add it like below :arrow_down:
`<button type='submit'>Get in touch<button>`

- [ ] Kindly, add the `hover` effect on the button as well in your css file to make your button look familiar with other form buttons :+1:

2022-09-28 14:11 UTC, Moise-code commented
hi there, kindly check all the changes are implemented you can consider this link
https://github.com/Moise-code/Portfolio-website/pull/4

2022-09-28 16:25 UTC, Moise-code commented
@HAMMAS-SALEEM 
please kindly check the implemented changes.

2022-09-29 07:51 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @Moise-code ✋ 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 08:17 UTC, merged