Desktop version of my portfolio
Moise-code/Portfolio-website pull request #5
Opened 2022-09-30 13:32 UTC by Moise-code

Desktop version of my portfolio :

In this project I have added:
responsiveness using media querries for two types of device frame; Mobile devices and desktop.

2022-09-30 14:02 UTC, nedjwab requested changes
# Changes Required ♻️
### Hi @Moise-code 

Nice job✔, I liked your implementation 🔥, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.
- Good design 🔥🔥🔥 , keep it up.😉

## (Changes Required) Aspects to improve: ♻️
You did great implementing  the project requirements 🔥🔥, but you still have some issues:  
Check the comments below 👇
  
## [Optional] suggestions:

-  Nothing to mention. 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-30 14:02 UTC, nedjwab commented on index.html
> +      <hr>
[ ] kindly change the `font color `of the technologies list and the title in this section to match the Figma template, the one used in the template is `#091E42` .🤓
Your design : 
![headerta3ou](https://user-images.githubusercontent.com/62156607/193285831-ac4b8a06-6419-4153-a434-712d457dfaea.PNG)

![icons](https://user-images.githubusercontent.com/62156607/193285382-052d5a9e-43c6-4ea0-bb2d-a414d6fd74b7.PNG)

Figma design : 
![designicons](https://user-images.githubusercontent.com/62156607/193285469-f39bab1b-3896-415e-b7b1-951c447c7c3d.PNG)
![header](https://user-images.githubusercontent.com/62156607/193285900-84986b8f-6acf-4356-a30b-77205d61e53a.PNG)

2022-09-30 14:02 UTC, nedjwab commented on Styles/styles.css
> +    display: grid;
nice use of the grid and flexbox  🔥🔥

2022-09-30 14:02 UTC, nedjwab commented on index.html
> +        <div class="work1-second-part">
[ ] kindly add a hover effect to your cards, so when we hover on with the mouse the description and dark opacity disappear and a See Project button appears at the bottom of the image and takes the whole image width mentioned button should take you to the Live Demo of the project or to the GitHub repository.👀
Your cards : 
![hoverta3ou](https://user-images.githubusercontent.com/62156607/193286555-f0c7a1dc-e271-4483-8be6-4094540de65c.PNG)

Figma design : 
![hoverdesign](https://user-images.githubusercontent.com/62156607/193286605-21a18138-c26e-4de6-99a0-1da72c586ec8.PNG)

2022-09-30 18:19 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @Moise-code , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 18:19 UTC, bobb-Rob commented on index.html
>              <li>Bootstrap</li>
- [ ] [REQUIRED] As mentioned by the previous reviewer, please the border for the list of technologies uses this `#8993A4` color and not `black`. Kindly change that so it fits with that of the Figma design. 

### Your design 
![image](https://user-images.githubusercontent.com/84156714/193331702-fcaf08f6-5c50-49c3-afb5-a0957159c024.png)

### Figma Design
![image](https://user-images.githubusercontent.com/84156714/193331908-76d19af7-c2e9-4a58-9a5a-f78c9210d8f2.png)

2022-09-30 18:19 UTC, bobb-Rob commented on index.html
> +    </div>
- [ ] [REQUIRED] Your navbar navigation items are missing. I noticed it was present when you submitted it for the first review. But now, it is gone. Kindly look into this and fix it. 
![image](https://user-images.githubusercontent.com/84156714/193332551-14f7f880-00c3-4164-827d-26a0c67bdff4.png)

2022-10-01 09:13 UTC, Gopxfs commented
# 🟢 STATUS: APPROVED 🟢

## Hello @Moise-code 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 09:38 UTC, merged